spring:
  application:
    name: WeChat
security:
  oauth2:
    client:
      clientId:
      clientSecret:
      accessTokenUri:
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      redirectUri: http://localhost:8080/api/auth/facebook
      scope: email,public_profile
    resource:
      userInfoUri: https://graph.facebook.com/me?fields=email,name