spring:
  application:
    name: WeChat
security:
  oauth2:
    client:
      clientId: 973886929758300
      clientSecret: 5991f5753ca558dc59f1d536570a7862
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      redirectUri: http://localhost:8080/api/auth/facebook
      scope: email,public_profile
    resource:
      userInfoUri: https://graph.facebook.com/me?fields=email,name